### ISSUE TITLE
[enhancement][qa] Make rota more robust to sluggish Slack API

### ISSUE THREAD

**Issue by kmaida** [kmaida/rota-slackbot#32]
Sometimes when Slack's API is sluggish responding, Rota gets hung up on async calls and doesn't seem to completely process functions before moving on too quickly. Add some functionality to handle race conditions on slow networks or poor connectivity.

**Comment by kmaida** [comment]
Completed; time will tell if this is fully solved.

**Comment by bemorr** [comment]
I'd be surprised if this was entirely due to sluggish responses from slack API. This was happening consistently everyday when I had it installed so had to remove the bot.

**Comment by kmaida** [comment]
I cannot reliably reproduce your issue. If you're able to detect the cause and submit a PR to resolve it, please feel free.
