### ISSUE TITLE
Using the stated Rotation Reminder example in the readme throws error

### ISSUE THREAD

**Issue by bemorr** [kmaida/rota-slackbot#35]
As per the below, I set a reminder using this text:

/remind @rota #bot-testing “liveops” assign the next user in the rotation using: `@rota "liveops" assign next` at 5:49pm

![Screenshot 2020-11-12 at 18 03 58](https://user-images.githubusercontent.com/16393820/98973008-7c015300-2513-11eb-828b-ee1e6f3f7af2.png)

I have a `liveops` rotation config'd: 

![Screenshot 2020-11-12 at 18 16 27](https://user-images.githubusercontent.com/16393820/98972856-4f4d3b80-2513-11eb-92a5-97be744fd9c6.png)

To which rota-bot complains:

![Screenshot 2020-11-12 at 18 07 23](https://user-images.githubusercontent.com/16393820/98971879-06e14e00-2512-11eb-90e8-cfcd53d992a7.png)

Please could you update your docs to reflect how this should be configured?

**Comment by kmaida** [comment]
Slackbot cannot issue commands to Rota. Slack doesn't allow bots to give other bots commands. It has to come from a user. The reminder needs to be used in the manner stated in the README: it's to remind the _currently assigned user_ to assign the next user.

**Comment by kmaida** [comment]
Confirmed as an intermittent (but not consistently reproducible) issue; I will take a look soon.

**Comment by kmaida** [comment]
<img width="823" alt="Screen Shot 2021-03-18 at 4 42 18 PM" src="https://user-images.githubusercontent.com/1884525/111694981-f2d39300-8808-11eb-8af2-1c37e8fd6a2c.png">

Note to self: most of the time, it works. Makes me think there might be some sort of weird race condition when using remind. Needs exploration

**Comment by kmaida** [comment]
Note: may be related to #32

**Comment by kmaida** [comment]
Closing, as I have been unable to duplicate the issue. I've added some logging in case it occurs in the future, so that I will be more easily able to track. I also upgraded Bolt and adjusted the recommendation for how to format the remind command. Using additional quotes has resulted in zero repro of the error for me in multiple workspaces at this time. Can reopen if issue persists at a later date.
